apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: circles.charlecd.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: charlecd.io
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                segments:
                  type: array
                  items:
                    type: object
                    properties:
                      key:
                        type: string
                      condition:
                        type: string
                      value:
                        type: string
                environments:
                  type: array
                  items:
                    type: object
                    properties:
                      key:
                        type: string
                      value:
                        type: string
                release:
                  type: object
                  properties:
                    name: string
                    tag: string
                    projects:
                      type: array
                      items:
                        type: object
                        properties:
                          name: string
                          repoURL: string
                          path: string
                          resources:
                            type: array
                            items:
                              type: object
                              properties:
                                kind: string
                                group: string
                                version: string
                                health: string
                                status: string
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: circles
    # singular name to be used as an alias on the CLI and for display
    singular: circle
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Circle
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - cl
