apiVersion: v1
kind: ServiceAccount
metadata:
  name: circlerr-gitops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: circlerr-gitops
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: circlerr-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: circlerr-gitops
subjects:
- kind: ServiceAccount
  name: circlerr-gitops
  namespace: circlerr
---
apiVersion: v1
kind: Service
metadata:
  name: circlerr-gitops
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: circlerr-gitops
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: circlerr-gitops
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: circlerr-gitops
  template:
    metadata:
      labels:
        app: circlerr-gitops
    spec:
      containers:
      - image: circlerr/circlerr-gitops:latest
        name: circlerr-gitops
        ports:
        - containerPort: 8080
      serviceAccountName: circlerr-gitops
