apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - circlerr-gitops-serviceaccount.yaml
  - circlerr-gitops-clusterrole.yaml
  - circlerr-gitops-clusterrolebinding.yaml
  - circlerr-gitops-service.yaml
  - circlerr-gitops-deployment.yaml
