/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/maycommit/circlerr/pkg/k8s/controller/apis/circle/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCircles implements CircleInterface
type FakeCircles struct {
	Fake *FakeCircleV1alpha1
	ns   string
}

var circlesResource = schema.GroupVersionResource{Group: "circlerr.io", Version: "v1alpha1", Resource: "circles"}

var circlesKind = schema.GroupVersionKind{Group: "circlerr.io", Version: "v1alpha1", Kind: "Circle"}

// Get takes name of the circle, and returns the corresponding circle object, and an error if there is any.
func (c *FakeCircles) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Circle, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(circlesResource, c.ns, name), &v1alpha1.Circle{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Circle), err
}

// List takes label and field selectors, and returns the list of Circles that match those selectors.
func (c *FakeCircles) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CircleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(circlesResource, circlesKind, c.ns, opts), &v1alpha1.CircleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CircleList{ListMeta: obj.(*v1alpha1.CircleList).ListMeta}
	for _, item := range obj.(*v1alpha1.CircleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested circles.
func (c *FakeCircles) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(circlesResource, c.ns, opts))

}

// Create takes the representation of a circle and creates it.  Returns the server's representation of the circle, and an error, if there is any.
func (c *FakeCircles) Create(ctx context.Context, circle *v1alpha1.Circle, opts v1.CreateOptions) (result *v1alpha1.Circle, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(circlesResource, c.ns, circle), &v1alpha1.Circle{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Circle), err
}

// Update takes the representation of a circle and updates it. Returns the server's representation of the circle, and an error, if there is any.
func (c *FakeCircles) Update(ctx context.Context, circle *v1alpha1.Circle, opts v1.UpdateOptions) (result *v1alpha1.Circle, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(circlesResource, c.ns, circle), &v1alpha1.Circle{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Circle), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCircles) UpdateStatus(ctx context.Context, circle *v1alpha1.Circle, opts v1.UpdateOptions) (*v1alpha1.Circle, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(circlesResource, "status", c.ns, circle), &v1alpha1.Circle{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Circle), err
}

// Delete takes name of the circle and deletes it. Returns an error if one occurs.
func (c *FakeCircles) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(circlesResource, c.ns, name), &v1alpha1.Circle{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCircles) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(circlesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.CircleList{})
	return err
}

// Patch applies the patch and returns the patched circle.
func (c *FakeCircles) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Circle, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(circlesResource, c.ns, name, pt, data, subresources...), &v1alpha1.Circle{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Circle), err
}
